image: node:12.16.1

pages:
  script:
  - yarn install
  - yarn build
  - rm -rf ./public
  - mv ./build ./public
  artifacts:
    paths:
    - public
  cache:
    paths:
      - node_modules
  only:
  - master
